import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: "#F9FAFB",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    marginTop: 10,
  },
  title: {
    fontSize: 26,
    fontWeight: "800",
    color: "#1F2937",
    letterSpacing: 0.2,
  },
  logoutButton: {
    backgroundColor: "#FEE2E2",
    borderRadius: 12,
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 60,
  },
  emptyText: {
    fontSize: 16,
    color: "#6B7280",
    textAlign: "center",
    fontWeight: "500",
  },
  cardContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#F3E8FF",
    elevation: 3,
    shadowColor: "#8B5CF6",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1F2937",
    marginBottom: 3,
  },
  cardDescription: {
    fontSize: 16,
    color: "#4B5563",
    marginBottom: 12,
    lineHeight: 20,
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  streakBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FEF3C7",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  streakText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#D97706",
    marginLeft: 4,
  },
  frequencyBadge: {
    backgroundColor: "#F3E8FF",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  frequencyText: {
    fontSize: 13,
    color: "#7C3AED",
    fontWeight: "600",
  },
  homebutton: {
    borderRadius: 12,
    alignSelf: "flex-end",
    backgroundColor: "#FEE2E2",
    marginBottom: 16,
  },
  leftaction: {
    width: "35%",
    backgroundColor: "#d54848ff",
    justifyContent: "center",
    alignItems: "flex-start",
    borderTopLeftRadius: 18,
    borderBottomLeftRadius: 18,
    paddingLeft: 20,
    marginBottom: 14,
    marginTop: 2,
  },
  rightaction: {
    width: "35%",
    backgroundColor: "#10B981",
    justifyContent: "center",
    alignItems: "flex-end",
    borderTopRightRadius: 18,
    borderBottomRightRadius: 18,
    paddingRight: 20,
    marginBottom: 14,
    marginTop: 2,
  },
});
